---
sudo: required
services:
  - docker
script:
  - docker run -t -v $(pwd):/powershell cvent/psscriptanalyzer:latest
  # CIM modules are not installed on Powershell 6 Core for Ubuntu
  # - docker run -t -v $(pwd):/test adminb/pester-runner:latest